CREATE TABLE IF NOT EXISTS cliente(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS produto(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nome TEXT NOT NULL,
	preco INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS pedido(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	data_pedido TEXT NOT NULL,
	id_cliente INTEGER NOT NULL,
	FOREIGN KEY(id_cliente) REFERENCES cliente(id)
);

CREATE TABLE IF NOT EXISTS item_pedido(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	quantidade INTEGER NOT NULL,
	id_pedido INTEGER NOT NULL,
	id_produto INTEGER NOT NULL,
	FOREIGN KEY(id_pedido) REFERENCES pedido(id),
	FOREIGN KEY(id_produto) REFERENCES produto(id)
);

